arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
      - LB1_joint
      - LBW_joint
      - LF1_joint
      - LFW_joint
      - RB1_joint
      - RBW_joint
      - RF1_joint
      - RFW_joint
      - cam_x_j
      - cam_y_j
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
